### ISSUE TITLE
advancedTestApp is crashing on Android and not compiling on iOS using Delphi 10.4

### ISSUE THREAD

**Issue by hraztan** [Spelt/ZXing.Delphi#101]
Hi
The advancedTestApp is crashing on Android and not compiling on iOS using Delphi 10.4. It seems that the FMX.Media.Android.pas and FMX.Media.AVFoundation.pas (and maybe the FastUtils.pas) are not compatible with Delphi 10.4. It works just fine with the original files coming with Delphi 10.4. But unfortunately, by using the originals, the app is VERY slow both on iOS and Android.
Kindly, advise

**Comment by hraztan** [comment]
Any suggestions for a third-party fast camera component for Firemonkey (iOS and Android) apart from winsoft? 
Are the Winsoft components fast enough?

**Comment by Spelt** [comment]
Hi

I’m actually not supporting the advanced camera anymore. In the next release of Zxing I will remove the advanced demo application because I get too many questions about it and this repo is about the ZXing lib anyway.

I’m using the WinSoft camera components with no problems. 
I’m using them for both iOS and Android and they are indeed fast and fluent. I’m also using the iOS build-in barcode scanner together with the ZXing and that works great too. Though this is optional.

Hope it helps.

Sincerely, Edward

**Comment by hraztan** [comment]
Totally understandable.

Just a question: Winsoft has different versions (implementations) for iOS and Android, or it's one version for both?

**Comment by Spelt** [comment]
two components, one for iOS and one for Android.

Op za 13 jun. 2020 om 20:32 schreef hraztan <notifications@github.com>:

**Comment by Martijn-T** [comment]
Hi, I see you mentioning the Winsoft camera. Could you give me a pointer on how to use this with the zxing library? We purchased the Winsoft Android Camera but are having trouble to get it to work with the Zxing scanning

**Comment by Spelt** [comment]
I dont give support on that. I dont give support at all. 

Thats being said: look at the examples. 

Sincerely Edward
