### ISSUE TITLE
Compability with Delphi 10.4

### ISSUE THREAD

**Issue by netsimarge** [Spelt/ZXing.Delphi#103]
Hello,

Will be there any compability work for Delphi 10.4? I tried the library with 10.4, got some issues.

Thank you...

**Comment by Spelt** [comment]
Yes there will be. Feel free to report any issues.

**Comment by netsimarge** [comment]
Hello again,

I modified FMX.Media.AVFoundation.pas and FMX.Media.Android.pas from 10.4 installation according to latest release of the example project. Finally, when I try to read a QR code on my Android device (32 bit compile) I get "Illegal instruction (4)" error from FastUtils.pas (yv12_to_rgba function). I know this isn't a direct issue with the ZXing library but without them I couldn't get barcode reading work, it's too slow. Well, I'm not an expert, hope I didn't do anything wrong. A working example with 10.4 project will be very appriciated...

**Comment by netsimarge** [comment]
By the way, I also tried to make FastUtils load "libfastutils-android-arm.a" instead of "libfastutils-android-32.a" this time I got stuck at TVersion.getVersionForNumber function 'version number needs to be between 1 and 40' control in ZXing.QrCode.Internal.Version.

**Comment by Spelt** [comment]
Hi

I’m actually not supporting the advanced camera anymore. In the next release of Zxing I will remove the advanced demo application because I get too many questions about it and this repo is about the ZXing lib anyway.

I’m using the WinSoft camera components with no problems.
I’m using them for both iOS and Android and they are indeed fast and fluent. I’m also using the iOS build-in barcode scanner together with the ZXing and that works great too. Though this is optional.

Hope it helps.

Sincerely, Edward
