### ISSUE TITLE
Advanced TestApp don't work D10.4 Patch 3

### ISSUE THREAD

**Issue by Gregory667** [Spelt/ZXing.Delphi#105]
The Advanced TestApp won't run. Neither in 32 bit nor in 64 bit.
I use Delphi 10.4 with patch 3 and Samsung Galaxy S8 (Android 9)

32 Bit: The App start and if i activate the switch to scan, it freezes. No camara Pic.

64 Bit: During starting of the app a message "Error loading ok.wav".
Camera can be activated but the picture is distorted and i get "External Exception 28" in the memo.
Camera do NOT focus. Snan not possible.
If i deactivate and activate the switch again, the image is no longer distorted. But the camera still doesn't focus.
And i get "External Exception 40" in the memo.

**Comment by Spelt** [comment]
Hi

I’m actually not supporting the advanced camera anymore. In the next release of Zxing I will remove the advanced demo application because I get too many questions about it and this repo is about the ZXing lib anyway.

I’m using the WinSoft camera components with no problems.
I’m using them for both iOS and Android and they are indeed fast and fluent. I’m also using the iOS build-in barcode scanner together with the ZXing and that works great too. Though this is optional.

Hope it helps.

Sincerely, Edward

**Comment by Spelt** [comment]
I will keep this one open for future reference and until 10.4.1 is out.
