### ISSUE TITLE
Delphi10.4.1 ios13.7 FmxTestApp not working

### ISSUE THREAD

**Issue by AppSep** [Spelt/ZXing.Delphi#109]
Hi, 
on click on "Start Camera" Button on a iPad the app crash with a execption.
ECaptureDeviceException.

But i think this is a problem from the TCameraComponent.

Maybe you can check this please?

Unit FMX.Media.AVFoundation
`
procedure TAVVideoCaptureDevice.RecordingRequestAccessForMediaTypeCompletionHandler(granted: Boolean);
var
  LMessage: string;
begin
  if granted then
    LMessage := string.Empty
  else
    LMessage := SUserRejectedCaptureDevicePermission;

  TThread.Synchronize(nil,
    procedure
    begin
      DoPermissionRequest(LMessage, granted); ----> exception here
    end);
end;
`

**Comment by Spelt** [comment]
The code above looks fine to me.

But the fmx camera is not the best camera. It does not perform very well.   If you need scanning and IOS only then you better off with scanning natively because scanning is build into IOS camera.  Look at WinSoft.sk 


Anyway, I uploaded an improvement of the fmxTestApp.  Maybe it will help.

**Comment by AppSep** [comment]
thank you, 
i have delete the complete delphi 10.4.1 and all registry keys, after a new delphi install it works.
