### ISSUE TITLE
Ean13

### ISSUE THREAD

**Issue by sametkayaoglu** [Spelt/ZXing.Delphi#137]
![ean13](https://user-images.githubusercontent.com/21238095/211380965-3198003f-15b8-459c-9d19-b66717b3083f.png)

hi ean13 doesn't read barcode

**Comment by Spelt** [comment]
Hi,

On which platform do you experience this ?

**Comment by sametkayaoglu** [comment]
i live on all platforms including windows
Actually, the first digit information at the beginning of the problem is too much, but I couldn't find the solution.

**Comment by Spelt** [comment]
Hi

I tried this barcode in several apps and some do recognize it and some don't. After further investigation I saw a weird thing: it looks like the barcode is corrupted somehow.  There is one bar on the left to many. It also looks weird. If you photoshop the left bar away it works.  See the image below. I think this is the cause. It seems not to get recognized as an EAN barcode because of this and thats why its failing.

![explain bad EAN13](https://user-images.githubusercontent.com/12660181/212479885-03ed384e-ebf4-4cd3-8b05-d8df125712d6.png)

**Comment by sametkayaoglu** [comment]
Hi
I noticed this too, but it reads on laser device and some libraries
The product belongs to a large food company, so it does not seem possible to change it.
Can a change be made to the Zxing infrastructure?

**Comment by Spelt** [comment]
Maybe its some kind of extra extension on EAN13. I tested it with other zxing libs but they don’t recognize it too. You can make changes, sure. I’m happy to test it. Op 14 jan. 2023 om 20:57 heeft sametkayaoglu ***@***.***> het volgende geschreven:﻿
Hi
I noticed this too, but it reads on laser device and some libraries
The product belongs to a large food company, so it does not seem possible to change it.
Can a change be made to the Zxing infrastructure?
