### ISSUE TITLE
about RGBLuminanceSource

### ISSUE THREAD

**Issue by sargon5000** [Spelt/ZXing.Delphi#18]
Hi!
Look at the code, please:
```
constructor TRGBLuminanceSource.RGBLuminanceSource(sourceBitmap: TBitmap;  w: Integer; h: Integer);
........
   luminances[offset + x] := red shl 16 or green shl 8 or blue;
```
But **luminances** was declared as array of byte.  In fact, it was only visible blue channel. 

I propose to replace it with the following:
`   luminances[offset + x] := round(0.2125*Red + 0.7154*Green + 0.0721*blue);`

Or without floating-point operations:
`   luminances[offset + x] := (3482*Red + 11721*Green + 1181*blue) shr 14;`

Best regards.

**Comment by Spelt** [comment]
Hi

I will take a look at the code and will come back to you.


Thanks,
Edward

**Comment by Spelt** [comment]
Thanks for your interest and suggestions.

Another person had the same question: https://github.com/Spelt/ZXing.Delphi/issues/7 

I tested all of the proposals (they all pass the tests)  and I will go with the 'without floating-point operations' because this one is the fastest.

`luminances[offset + x] := (3482*Red + 11721*Green + 1181*blue) shr 14;`

Weird this is that the original code just worked.

I commited it and pushed it to the 3.0 branch which will be released after a last standing bug in the newly added DataMatrix is fixed. Mind you: this branch will **break** your existing code because of file/folder structure changed.
