### ISSUE TITLE
These barcodes are not recognized

### ISSUE THREAD

**Issue by csm101** [Spelt/ZXing.Delphi#47]
Hi,
   these QRCodes are not recognized at all by ZXing (one even raises a "divide by zero" error)
 I think that they aren't recognized even by the original ZXing.net.
  A workaround is to use the TDecodeHintType.PURE_BARCODE and  TDecodeHintType.TRY_HARDER_WITHOUT_ROTATION hints, but I don't think they can be used if the image is acquired by a camera (which is not the case of my application, so I am fine with them)

 Only 3 barcodes on a sample of 100 barcodes (all using the same qr-code format, just different content) show these problems.

 P.s: the "divide by zero" exception does not happen in .net because in .net float divide by zero returns "NaN " without raising any exception.

![1](https://cloud.githubusercontent.com/assets/5736859/20794190/404634b6-b7cb-11e6-87b6-fbbd7d1c310a.jpg)
![02365230594cog00000059](https://cloud.githubusercontent.com/assets/5736859/20794191/4048bd9e-b7cb-11e6-8cb4-2189c9b08bcc.jpg)
![02365230594cog00000109](https://cloud.githubusercontent.com/assets/5736859/20794192/404c067a-b7cb-11e6-9ecc-a01d33f2dd3b.jpg)

**Comment by Spelt** [comment]
Hi Carlo,

Thanks!

It apparently is by design. See comments from Sean Owen:  https://github.com/zxing/zxing/issues/I216 

Wondering now why PURE_BARCODES is not the deafult because everything gets grayscaled and binarized anyway. Huge colour pics get scanned too.  Did also some speed testing and there is no real word difference.

About the exception:
I released a small patch for the "divide by zero" exception in your cases. Somehow it does also not happen in a FM application.  I also added an extra unit test. See: https://github.com/Spelt/ZXing.Delphi/commit/cbcffc6c14d410ca5599e0c80ad64f9524a070b2
