### ISSUE TITLE
FPC port.

### ISSUE THREAD

**Issue by LongDirtyAnimAlf** [Spelt/ZXing.Delphi#71]
Hi,

For the last few days I have been working to get your very nice lib working with FPC and Lazarus.
The result is here:

https://github.com/LongDirtyAnimAlf/ZXing.Delphi

Would you be interested in bringing things together by a pull-request ?!
The new source also contains some bugfixes ... ;-)

Greetings, Alfred.

**Comment by Spelt** [comment]
Hi Alfred

Sorry I did not get back to you. 

I'm not working on Lazarus myself but feel free to use the source anyway you like. I'm not interested myself in adding support of another dev tool because of limited time and added complexity to the project.

If you find a bug or have bug fix, it would be great if you report it.  

Thanks,
Edward
