### ISSUE TITLE
Camera not actually released

### ISSUE THREAD

**Issue by iwan-c-sugeng** [Spelt/ZXing.Delphi#86]
Hi, i've using this library on Delphi Rio 10.3.2, i found out that when i set the camera active to false, it doesn't really release the camera handle, when i try to open another app that use the camera, the app complain that the camera is in use. 

After comparing the FMX.Media.Android from EvB code and from Latest Delphi Rio Code, found out that in your code the camera released on the Destroy event, while on the Delphi Rio Code, it is in the StopCapture method. I've tried it and it is working

Step to reproduce:
- Open form with camera and set it to active
- Close that form and make sure to set the camera.Active to false before closing
- switch to native camera app
- switch back to our apps and try to open the form with the camera,will generate “getParameters failed (empty parameters)” error

note:
- i'm using a face detection app, and it also report that the camera is still in use
- The same code is used after modifying your FMX.Media.Android and it run correctly

Contact me if you want to see my update, so you can merge it to your code if not a problem, i'm seeing some new routine in Rio so i don't know how to handle backward compatibility

**Comment by Spelt** [comment]
Hi

Dmx, yes show me the update or attach a Git patch. Would be great!


Thanks
Edward

**Comment by iwan-c-sugeng** [comment]
Hi,

I've attach my patch, thanks

[FMX.Media.Android.zip](https://github.com/Spelt/ZXing.Delphi/files/3518488/FMX.Media.Android.zip)

**Comment by Spelt** [comment]
Hi Iwan

In the DoStartCapture you have this code:

 CapturePollingTimer := TTimer.Create(nil);
 CapturePollingTimer.Interval := FCaptureTimerInterval;
 CapturePollingTimer.OnTimer := OnCaptureTimer;

You should remove this because CapturePollingTimer is already created in
the OnCreate and freed in the onDestroy.  Otherwise this will cause
problems.

Your patch solved the problem but it causes another problem. The app
crashes when I switch the camera to On to Off to On.


Any ideas?











Op di 20 aug. 2019 om 05:01 schreef dmx78 <notifications@github.com>:

**Comment by iwan-c-sugeng** [comment]
Hi,

I've checked my code, the create CapturePollingTimer code from DoStartCapture, is originally from the original Embarcadero Delphi Rio Code, and i forget to remove it, while on the OnCreate event, it is from your code which not remarked as added.

I'm attaching my test project, and it work well with the On Off On Off .. the camera. And even when the apps move to background, it is correctly calling the stopcapture method and stop the camera, the problem is that it is not yet handled correctly to set switch to correct state, but it can be added easily

This project have my custom class to wrap you AdvanceTestApp demo
[Project7.zip](https://github.com/Spelt/ZXing.Delphi/files/3521297/Project7.zip)

**Comment by Spelt** [comment]
Thanks,

It looks like somehow when the camera is dynamically created problems are
gone.

I changed and simplified the Advanced demo and uploaded it to gitHub.  I
created a new small version because of a memleak fix past week.

BUT: Because some files of the camera speed tweak used are closed source I
do make a new recommendation: use a commercial camera lib.WinSoft has a
decent one and you get the source + support.


Many thanks!

Sincerely,
Edward



Op di 20 aug. 2019 om 17:05 schreef dmx78 <notifications@github.com>:

**Comment by iwan-c-sugeng** [comment]
Hi,

Hope you still can read this closed issue, don't know how it work and i
don't want to mess up your issue just for this message.
I've just wondering, is it possible to submit your code to GetIt manager,
your Barcode Scanner library is wonderful, easy to use and fast. I'm asking
about the licensing issue with the camera speed up code. If possible, i
encourage you to submit the code to Embarcadero

Thank you

**Comment by Spelt** [comment]
Hi

There are no plans to create a component of the zxing lib.  

About the camera. Its actually not mine tweak but Eric van Bilsen. Anyway embarcadero is aware of the tweak because its already reported in quality central.  

I do recommend another camera component because in the used tweak there is a dependency lib which Eric has the source only.  
Embarcadero should rework the camera component but they cant do everything. 

Thanks for the compliment.




> Op 23 aug. 2019 om 18:06 heeft dmx78 <notifications@github.com> het volgende geschreven:
> 
> Hi,
> 
> Hope you still can read this closed issue, don't know how it work and i
> don't want to mess up your issue just for this message.
> I've just wondering, is it possible to submit your code to GetIt manager,
> your Barcode Scanner library is wonderful, easy to use and fast. I'm asking
> about the licensing issue with the camera speed up code. If possible, i
> encourage you to submit the code to Embarcadero
> 
> Thank you
>

**Comment by ettiennedup** [comment]
hi

i wonder if you can assist. we bought the component from winsoft and they are not replying to an error . it seems as though there is a bug in the component when using android 9.0.  7.0 and 8.0 works fine. the app just closes down

**Comment by Spelt** [comment]
I cant help you debugging someone else its software. What I can do is ask
also.

Its probably a change in an api which needs updating. Mobile is a fast
pacing world.





Op ma 21 okt. 2019 om 03:35 schreef ettiennedup <notifications@github.com>:

**Comment by ettiennedup** [comment]
Thanks

I also think it is that but I cant debug . Bummer and I paid so much for the software

 

Regards
Ettienne du Plessis 
Cell: 0781307154

Tel : 0837269376

 <http://www.programmic.co.za/> http://www.programmic.co.za

http://www.docsecure.co.za <http://www.docsecure.co.za/>

**Comment by Spelt** [comment]
Dont you have the source?

**Comment by iwan-c-sugeng** [comment]
Winsoft have a goox support, i talk to him also, very helpful, maybe he is
busy

**Comment by ettiennedup** [comment]
Hi 

Well he was responding to me until I asked this question last week . I am ready to go to production on this and my customer is not happy as I cant resolve the issue. I think it might be because of android version 9 .

And I don’t have a device I can debug on.

 

So yes I am also not happy . Eric could at least have returned my mail , but this is not your problem.

 

I will have to find an alternative if this is the level of support I am going to get

 

Thanks anyways

 

 

Regards
Ettienne du Plessis 
Cell: 0781307154

Tel : 0837269376

 <http://www.programmic.co.za/> http://www.programmic.co.za

http://www.docsecure.co.za <http://www.docsecure.co.za/>
