### ISSUE TITLE
Please added and fixed

### ISSUE THREAD

**Issue by amidomaru89** [Spelt/ZXing.Delphi#95]
Please added and fixed CodaBar
This code not have erros, but not working.
Please help.
[https://github.com/amidomaru89/file-CodaBar-for-zXing-Delphi/blob/master/ZXing.OneD.CodaBarReader.pas](url)

**Comment by Spelt** [comment]
Hi

I understand that you have a problem with Codabar?

Can you provide a failing case? 

Sincerely Edward

**Comment by amidomaru89** [comment]
Hi
Here is an example
This 100% CodaBar
I'm tested on my phone from application BarcodeScanner 
![FJIMG_20190909_164304](https://user-images.githubusercontent.com/21118653/78176893-ecb49d00-7465-11ea-93c1-930192620734.jpg)
![FJIMG_20190910_162903](https://user-images.githubusercontent.com/21118653/78176909-f2aa7e00-7465-11ea-9ec1-72c0339dfc3b.jpg)

**Comment by Spelt** [comment]
Thanks. 

I will check it soon. Don’t no exactly when but its on the list.

**Comment by Spelt** [comment]
With which phone did you test it with? And which model?

**Comment by amidomaru89** [comment]
Elephone P9000 with custom LinageOS 13, Xiaomi Mi 9T, Xiaomi mi 8 Lite and ofter with Meizu, Samsung and Sony

**Comment by Spelt** [comment]
Ok I did not understand you. Sorry about that.

Codabar is not converted yet and you pointed me to source which you've created but it does not work yet and you want me to debug it for you.  I will not debug it for you because I dont have an immediate need for Codabar and because i'm not working for you ;-)

However, what I did is created a new Codabar branch with my own conversion/translation and unit test for you. As a starting point.  Its not working yet. 

Hope it helps!

Sincerely, Edward

I'm closing this issue but please reopen or create a new one if you or someone else got it to work,
